# Generated by Django 3.2.9 on 2023-02-08 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230205_0008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
