# Generated by Django 3.2.9 on 2023-01-28 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('identifier', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('image', models.FileField(max_length=255, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('profile_photo', models.ImageField(default='profile_photos/default/default.jpg', upload_to='profile_photos/')),
                ('banner', models.ImageField(default='banners/default.jpg', upload_to='banners/')),
            ],
        ),
        migrations.AddIndex(
            model_name='usermedia',
            index=models.Index(fields=['user'], name='MediaManage_user_id_1e99d7_idx'),
        ),
    ]
