# Generated by Django 3.2.9 on 2023-02-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaManager', '0002_alter_usermedia_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/default/default.png', upload_to='profile_photos/'),
        ),
    ]
