# Generated by Django 3.2.9 on 2023-01-27 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('fullname', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(default='profile_photos/default/default.jpg', upload_to='profile_photos/')),
                ('banner', models.ImageField(default='banners/default.jpg', upload_to='banners/')),
                ('description', models.CharField(default='#CS Assoc. Prof 3 Social Media Co-chair', max_length=499)),
            ],
        ),
        migrations.AddIndex(
            model_name='userdata',
            index=models.Index(fields=['user'], name='accounts_us_user_id_3d5fe8_idx'),
        ),
    ]
